### ISSUE TITLE
Harvesting opportunity data

### ISSUE THREAD

**Issue by MelanieAbraham** [openactive/developer-documentation#16]
https://www.google.com/url?q=https://docs.google.com/document/d/1JW4GXXWOfJIFhAhzaCh-VU2AQm-O8Mk1NU4fZiuHZTA/edit?usp%3Dsharing&source=gmail&ust=1539175539922000&usg=AFQjCNGFcEOYLX5pvwH6qQI5laop3JTXbg

This document is basically done - needs a little addition if we're just pushing Live the changes Pete made to the status page (assuming we're not going to change the look of the status page at the moment)

**Comment by nickevansuk** [comment]
Have added as-is with links to the other tutorials removed for now
