### ISSUE TITLE
None of the optional fields in the `Concept` documentation page are Arrays or Urls.

### ISSUE THREAD

**Issue by 9Dave9** [openactive/developer-documentation#28]
[](https://github.com/openactive/developer-documentation/blob/master/docs/data-model/types/concept.md)

The examples say `Array's of urls`:

ie: `"altLabel": "Speedball"` should either be `"altLabel": ["Speedball"]` or the description text should point out that that there are two possible types(I have am not sure which one is true).

confusing :/

**Comment by nickevansuk** [comment]
This has now been resolved!
