### ISSUE TITLE
Incorrect datetime format in idTemplates section in Schedule guidance

### ISSUE THREAD

**Issue by lukehesluke** [openactive/developer-documentation#30]
https://developer.openactive.io/publishing-data/schedules#using-templates

> When such ScheduledSessions are included, the Schedule must also include an idTemplate, such as the below, which matches the pattern of the @id of the ScheduledSessions (noting the startDate placeholder must use a string format of YYYY-MM-DDThh-mm-ssZ (e.g. 1997-07-16T19-20-00Z):

I expect that this is supposed to be

> YYYY-MM-DDThh:mm:ssZ (e.g. 1997-07-16T19:20:00Z) to match ISO datetimes

**Comment by nickevansuk** [comment]
This is a great point - the reason for this is the URL structure, however colons are actually allowed within the URL structure (https://tools.ietf.org/html/rfc3986#section-3.3), and existing implementations are actually using colons!

**Comment by nickevansuk** [comment]
Have resolved by updating the docs to use colons, consistent with all implementations
