### ISSUE TITLE
Add documentation for data users to ensure they use BigInt when processing RPDE modified to prevent overflow in languages where the default integer type would overflow

### ISSUE THREAD

**Issue by lukehesluke** [openactive/developer-documentation#56]
This is caused primarily by SQL Server’s [timestamp](https://msdn.microsoft.com/en-us/library/ms182776%28v=SQL.90%29.aspx) or [rowversion](https://msdn.microsoft.com/en-GB/library/ms182776.aspx) (as referenced [here](https://openactive.io/realtime-paged-data-exchange/#incrementing-unique-change-number)), which is cast to a SQL Server `BIGINT` on the way out of the db (`SELECT CAST([version] AS BIGINT) FROM [dbo].[mytable]`)

Raise an issue for RPDE that limits the `modified` and `id` to be 64-bit if they are numbers (what to do for JS, C#, etc)

------

Add to this branch of the gitbook project for dev docs 268 (https://app.gitbook.com/o/-LJTExWaXZFqcFJ_lZwF/s/-LOMz1IIOd5fl4xzfUYb/~/changes/268/using-data/harvesting-opportunity-data-1)

-----

Output:

- Developer docs: This is in the Harvesting Opportuniy data page in the dev docs PR #268 https://app.gitbook.com/o/-LJTExWaXZFqcFJ_lZwF/s/-LOMz1IIOd5fl4xzfUYb/~/changes/268/using-data/harvesting-opportunity-data
- RPDE issue: https://github.com/openactive/realtime-paged-data-exchange/issues/103

**Comment by lukehesluke** [comment]
This issue should be close-able when the draft https://app.gitbook.com/o/-LJTExWaXZFqcFJ_lZwF/s/-LOMz1IIOd5fl4xzfUYb/~/changes/268/using-data/harvesting-opportunity-data is merged

**Comment by nickevansuk** [comment]
Merged
