### ISSUE TITLE
How to set up a dev environment with an IDE (VSCode), linter, etc.

### ISSUE THREAD

**Issue by civsiv** [openactive/developer-documentation#57]
Step by step (for JS dev):

- How to set up IDE
- What plugins are useful
- Connect VSCode to GitHub
- JSDoc - VSCode settings etc
- ESLint

Same as above for .NET dev

**Comment by civsiv** [comment]
Docs here: https://app.gitbook.com/o/-LJTExWaXZFqcFJ_lZwF/s/bE7Sev9Msu9B0xnKKEpA/~/changes/2/setting-up-the-developer-environment

**Comment by nickevansuk** [comment]
Looks good. Merged here: https://contributor.openactive.io/setting-up-the-developer-environment
