### ISSUE TITLE
Conventions on commit message names and PRs etc; including dev process

### ISSUE THREAD

**Issue by civsiv** [openactive/developer-documentation#58]
Suggested process:

1. Clone 
2. Create a branch
3. Fix
4. Run tests locally (e.g. `$ npm run lint-fix` `$ npm test`)
5. Create a draft PR
6. Check tests in CI pass (and fix if necessary)
7. Move PR out of draft 
8. Add a reviewer
9. Review - maybe have a call, comment, and ultimately approved by reviewer
10. Merged into master by contributor
11. Final tests run in master
12. May trigger recreation of other tools; contributor to review these downstream auto-generated PRs and merge(note need to reference diagram / other approach to know which repos to check downstream)

Note: keep PRs small where possible, try not to have long-running dev branches

Conventional commits: Using `feat:` prefix etc. Branch names (`feature/` noting `coverage/` is an exception in test suite)

- Pre-commit hooks (Husky), and what to do if commits fail
- Referencing packages locally in package.json (to test dependency changes locally)
- Debugging in VSCode with different projects (local settings etc)
   - Include breakpoints

**Comment by nickevansuk** [comment]
Reviewed 👍  https://contributor.openactive.io/development-process
