### ISSUE TITLE
Define "bookings" and "listings" clearly

### ISSUE THREAD

**Issue by nickevansuk** [openactive/developer-documentation#59]
"Bookings" and "Listings" are mentioned in https://developer.openactive.io/publishing-data/data-feeds/types-of-feed but not explained. These concepts should be clearly defined and explained in the docs.

**Comment by howaskew** [comment]
Data Feeds

Overview
To take advantage of the OpenActive ecosystem of data users, data must be published via open data feeds.

There are a few common patterns for these feeds of data about opportunities for sport and physical activity, which we call ‘opportunity data’. This includes general information about activities and facilities, sometimes referred to as ‘listings data’, and specific time-based events or slots that can be booked, known as ‘bookable data’.

These feeds must be published using the OpenActive Realtime Paged Data Exchange (RPDE) specification, which provides a mechanism to allow systems to synchronise database state in near-realtime.

https://app.gitbook.com/o/-LJTExWaXZFqcFJ_lZwF/s/-LOMz1IIOd5fl4xzfUYb/~/changes/272/publishing-data/data-feeds

**Comment by howaskew** [comment]
Also added a link to data quality framework, as per the pull request on data catalogs

**Comment by nickevansuk** [comment]
Interestingly ChatGPT was helpful here (https://chat.openai.com/share/178b5db1-bda1-4ba4-a0f3-594e78489add).

Approved and published to https://developer.openactive.io/publishing-data/data-feeds and https://developer.openactive.io/publishing-data/data-quality
